FROM node:lts-alpine

WORKDIR /app

RUN npm install -g serve

COPY ../front-end/package*.json ./
RUN npm install

COPY ../front-end/vercel.json ./
COPY ../front-end/vite.config.js ./
COPY ../front-end/index.html ./
COPY ../front-end/public/ ./public
COPY ../front-end/src/ ./src

ENV VITE_BACKEND_URL=http://localhost:8080

ENV PORT 3000

EXPOSE 3000

RUN npm run build

CMD serve --config ../vercel.json dist