FROM node:lts-alpine

WORKDIR /app

RUN npm install -g serve

COPY package*.json .
RUN npm install

COPY vite.config.js .
COPY index.html .
COPY public/ ./public
COPY src/ ./src

RUN npm run build

CMD serve dist
