FROM node:lts-alpine

WORKDIR /app

COPY package*.json .
RUN npm install
RUN npm install -g serve

COPY vite.config.js .
COPY index.html .
COPY public/ ./public
COPY src/ ./src

RUN npm run build

CMD serve dist
