FROM node:lts-alpine

WORKDIR /app

RUN npm install -g serve

COPY package*.json ./
RUN npm install

COPY vercel.json ./
COPY vite.config.js ./
COPY index.html ./
COPY public ./public
COPY src ./src

ENV VITE_BACKEND_URL=https://rulemaking-influence-explorer-back-end-o6il5tt6qq-pd.a.run.app

ENV PORT 3000

EXPOSE 3000

RUN npm run build

CMD serve --config ../vercel.json dist