version: '3.8'

services:
  app:
    build:
      context: ../back-end
      dockerfile: dockerfile
    container_name: rule-making-influence-back-end
    restart: always
    working_dir: /var/www/
    volumes:
      - ../back-end/src:/var/www
      - ../back-end/data:/data
      - ../back-end/config:/config

  nginx:
    image: nginx:1.19-alpine
    container_name: rule-making-influence-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ../back-end/src:/var/www
      - ../back-end/nginx:/etc/nginx/conf.d

  front-end:
    build:
      context: ../front-end/
    container_name: rule-making-influence-front-end
    restart: always
    working_dir: /app
    ports:
      - "80:3000"