FROM php:8.0.2-fpm

# PORT 9000 is automatically exposed with the fpm image

RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    vim \
    unzip

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www

COPY . .

#COPY ../config /var/www/config
#COPY ../src /var/www/src
#COPY ../composer.json /var/www/composer.json
#COPY ../composer.lock /var/www/composer.lock

# Set the COMPOSER_ALLOW_SUPERUSER environment variable to 1
ENV COMPOSER_ALLOW_SUPERUSER=1

CMD composer install && php-fpm