# Use a PHP base image with PHP-FPM and Composer installed
FROM php:8.0.2-fpm

# Install additional dependencies as needed
RUN apt-get update -y \
    && apt-get install -y nginx

COPY gcp/nginx.conf /etc/nginx/sites-enabled/default
COPY entrypoint.sh /etc/entrypoint.sh
COPY --chown=www-data:www-data . /var/www/

RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    vim \
    unzip

# Install Composer globally
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set working directory for Composer operations
WORKDIR /var/www/

# Install PHP dependencies with Composer
RUN composer install --no-dev

ENV PORT 80

# Expose port 80 for Nginx
EXPOSE 80 443

ENTRYPOINT ["sh", "/etc/entrypoint.sh"]